<a href="https://colab.research.google.com/github/veyselberk88/Data-Science-Tools-and-Ecosystem/blob/main/lec11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="./ccsf.png" alt="CCSF Logo" width=200px style="margin:0px -5px">

# Lecture 11: Functions

Associated Textbook Sections: [8.0, 8.1](https://ccsf-math-108.github.io/textbook/chapters/08/Functions_and_Tables.html)

---

## Overview

* [Defining Functions](#Defining-Functions)
* [Apply](#Apply)

---

## Set Up the Notebook

In [ ]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

---

## Defining Functions

---

### `def` Statements

User-defined functions give names to blocks of code.


``` python
def spread(values):
    """Return the spread of the values.

    Keyword argument:
    values: an array-like object of numerical values
    """
    value_spread = max(values) - min(values)
    return value_spread
```

---

### The First Line


``` python
def spread(values):

```

* `def` is a Python keyword that indicates you are defining a function
* `spread` is the name of the function. This is how the function can be referenced.
* `values` is the function argument.
    * _A function may have 0, 1, 2, ... arguments._
    * `values` serves as a placeholder in the definition for whatever input you actually provide.
    * You can set the default value for an argument with an assignment statement.
* The `:` is required.

###functions default return value is None

---

### The Docstring

``` python
    """Return the spread of the values.

    Keyword argument:
    values: an array-like object of numerical values
    """
```

* The docstring provides documentation on what the function does.
* Everything between the triple double quotes is included in the docstring.

---

### The Body


``` python
    value_spread = max(values) - min(values)
    return value_spread
    
```

* `value_spread = ...` and `return value_spread` are part of the body of the function.
    * This is the code that you have named as `spread`.
    * The spacing is important for identifying the body.
* `return value_spread` is the return statement for the function. _A function does not need to have a return statement._

---

In [ ]:
def spread(values):
    """Return the spread of the values.

    Keyword argument:
    values: an array-like object of numerical values
    """
    value_spread = max(values) - min(values)
    return value_spread

---

In [ ]:
spread?

Signature: spread(values)
Docstring:
Return the spread of the values.

Keyword argument:
values: an array-like object of numerical values
File:      /tmp/ipykernel_198/2414150103.py
Type:      function

---

### Demo: Functions

Create a simple function with one argument and demonstrate using it.

In [ ]:
def mult_10(some_number):
    value=some_number *10
    return value

In [ ]:
mult_10(6)

60

In [ ]:
num = 3.45

In [ ]:
mult_10(num)

34.5

In [ ]:
mult_10(some_number=num)

34.5

In [ ]:
...

---

### Demo: Scope

Illustrate the concept of scope using functions.

In [ ]:
mult_10(5)

50

In [ ]:
value=10

In [ ]:
mult_10(5)

50

In [ ]:
#A NameError when some_number is referenced outside of the function body
...

In [ ]:
some_number = ...

In [ ]:
...

In [ ]:
...

In [ ]:
...

In [ ]:
#A NameError when new_variable is referenced outside of the function body
...

In [ ]:
an_input = ...
...

In [ ]:
#A NameError when new_variable is referenced outside of the function body
...

---

### Demo: Type Agnostic

Show that Python functions are type agnostic.

In [ ]:
mult_10('a')

'aaaaaaaaaa'

In [ ]:
'a'*10

'aaaaaaaaaa'

---

### Demo: Multiple Arguments

Create a function that calculates the Hypotenuse Length of a Right Triangle using:

Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length satisfies:

$ h^2 = x^2 + y^2 \hspace{20 pt} \iff \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $

In [ ]:
def hypotenuse(x, y):
    h = np.sqrt(x*x + y*y)
    return h

In [ ]:
hypotenuse(3,4)

5.0

In [ ]:
hypotenuse(y=3,x=4)

5.0

---

### Demo: No Arguments

Create and use a function that has no arguments.

In [ ]:
def my_pi():
    return np.pi

In [ ]:
my_pi()

3.141592653589793

In [ ]:
# You need to use the () for the function call
...

---

## Apply

---

### Apply

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
for a in np.arange(5):
    b = mult_10(a)
    print(b)

0
10
20
30
40


* The apply method creates an array by calling a function on every element in input column(s)
    * First argument: The function to apply
    * Other arguments: The input column(s)
* Produces an array containing the output of the function on each input column element.
* Example application: `table_name.apply(function_name, 'column_label')`


---

### Demo: Apply

Show how to apply a function to a table.

In [ ]:
charge_table = Table().with_columns(
    'Item Number', np.arange(1, 5),
    'Charge', make_array('$4.30', '$120.21', '$10.50', '$325.51')
)
charge_table

Item Number | Charge
1           | $4.30
2           | $120.21
3           | $10.50
4           | $325.51

In [ ]:
# The data type of the charges is causing an error
...

In [ ]:
def dollar_to_float(a_string_dollar_amount):
    b = a_string_dollar_amount.replace('$', '')
    return float(b)

In [ ]:
dollar_to_float('$5.6')

5.6

In [ ]:
charge_table.apply(dollar_to_float, 'Charge')

array([   4.3 ,  120.21,   10.5 ,  325.51])

In [ ]:
c = charge_table.apply(dollar_to_float, 'Charge')
charge_table2 = charge_table.with_column('new_charge', c)
charge_table2

Item Number | Charge  | new_charge
1           | $4.30   | 4.3
2           | $120.21 | 120.21
3           | $10.50  | 10.5
4           | $325.51 | 325.51

In [ ]:
charge_table2.apply(mult_10, 'new_charge')

array([   43. ,  1202.1,   105. ,  3255.1])

---

Use the `apply` method with a function with multiple arguments.

In [ ]:
triangle_info = Table().with_columns(
    'x', make_array(15, 7, 5, 21),
    'y', make_array(1, 0, 2, 32)
)
triangle_info

x    | y
15   | 1
7    | 0
5    | 2
21   | 32

In [ ]:
hypotenuses = triangle_info.apply(hypotenuse, 'x', 'y')
triangle_info.with_column('h', hypotenuses)

x    | y    | h
15   | 1    | 15.0333
7    | 0    | 7
5    | 2    | 5.38516
21   | 32   | 38.2753

---

## Attribution

This content is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)</a> and derived from the <a href="https://www.data8.org/">Data 8: The Foundations of Data Science</a> offered by the University of California, Berkeley.

<img src="./by-nc-sa.png" width=100px>